apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-demo
  labels:
    app: env-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: env-demo
  template:
    metadata:
      labels:
        app: env-demo
    spec:
      containers:
      - name: env-demo
        image: kennyk65/spring-cloud-aws-environment-demo:1
        ports:
        - containerPort: 80
