# server:
#   servlet:
#     session:
#       tracking-modes: cookie


spring:
  application.name: client
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e0737f257e60beee40e6
            clientSecret: 2dbe809c39965b6921426b964099bed04fcc4d6f
          google:
            client-id: 1034653135442-j27ijg9om55p2ascg1gurbj3sp46iuek.apps.googleusercontent.com
            client-secret: kmcGAl5meGxwwUdvHnnmv_Se

logging:
  level:
    org.springframework.security.oauth2: DEBUG


        #   oidc-client:
        #     client-id: "oidc-client"
        #     client-secret: "secret"
        #     client-name: "Client for OpenID Connect"
        #     provider: "my-oauth-provider"
        #     scope: "openid"
        #     redirect-uri: "http://localhost:8080/login/oauth2/code/oidc-client"
        #     client-authentication-method: "client_secret_basic"
        #     authorization-grant-type: "authorization_code"

        # provider:
        #   my-oauth-provider:
        #     authorization-uri: "http://localhost:9000/oauth2/authorize"
        #     token-uri: "http://localhost:9000/oauth2/token"
        #     user-info-uri: "http://localhost:9000/userinfo"
        #     user-info-authentication-method: "header"
        #     jwk-set-uri: "http://localhost:9000/oauth2/jwks"
        #     user-name-attribute: "name"


# spring:
#   application:
#     name: Client
#   security:
#     oauth2:
#       client:
#         registration:
#           oidc-client:
#             client-id: "oidc-client"
#             client-secret: "secret"
#             client-name: "Client for OpenID Connect"
#             provider: "my-oauth-provider"  # Ensure this is included
#             scope: "openid"
#             redirect-uri: "http://localhost:8080/login/oauth2/code/oidc-client"
#             client-authentication-method: "client_secret_basic"
#             authorization-grant-type: "authorization_code"

#         provider:
#           my-oauth-provider:
#             authorization-uri: "http://localhost:9000/oauth2/authorize"
#             token-uri: "http://localhost:9000/oauth2/token"
#             user-info-uri: "http://localhost:9000/userinfo"
#             user-info-authentication-method: "header"
#             jwk-set-uri: "http://localhost:9000/oauth2/jwks"
#             user-name-attribute: "name"

