create table refresh_tokens (id integer generated by default as identity (start with 1), expiry_date timestamp(6), token varchar(255), user_id bigint, primary key (id));
create table roles (id bigint not null, name varchar(255), primary key (id));
create table users (id bigint not null, password varchar(255), username varchar(255), enabled int, primary key (id));
create table users_roles (user_info_id bigint not null, roles_id bigint not null, primary key (user_info_id, roles_id));
create table AUTHORITIES (username varchar(255), authority varchar(255))
create sequence roles_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
